language: python
python:
        - 2.7

addons:
  apt:
    packages:
      # generic packages
      - gcc
      - gfortran
      - libblas-dev
      - liblapack-dev
      # lal dependencies
      - pkg-config
      - zlib1g-dev
      - libgsl0-dev
      - swig
      - bc
      # nds2 dependencies
      - libsasl2-2
      # misc python dependencies
      - texlive-latex-extra
      - texlive-fonts-recommended
      - dvipng
      - libhdf5-serial-dev

env:
  global:
    - SWIG_VERSION="3.0.8"
    - FFTW_VERSION="3.3.4"
    - LAL_VERSION="6.15.0"
    - LALFRAME_VERSION="1.3.0"
    - LIBFRAME_VERSION="8.20"
    - LDAS_TOOLS_VERSION="2.4.1"
    - NDS2_CLIENT_VERSION="0.10.4"
    - LALSIM_VERSION="1.4.1"
    # tarballs
    - SWIG_="https://github.com/swig/swig/archive/rel-${SWIG_VERSION}.tar.gz"
    - FFTW="http://www.fftw.org/fftw-${FFTW_VERSION}.tar.gz"
    - LDAS_TOOLS="http://software.ligo.org/lscsoft/source/ldas-tools-${LDAS_TOOLS_VERSION}.tar.gz"
    - LIBFRAME="http://software.ligo.org/lscsoft/source/libframe-${LIBFRAME_VERSION}.tar.gz"
    - LAL="http://software.ligo.org/lscsoft/source/lalsuite/lal-${LAL_VERSION}.tar.gz"
    - LALFRAME="http://software.ligo.org/lscsoft/source/lalsuite/lalframe-${LALFRAME_VERSION}.tar.gz"
    - NDS2_CLIENT="http://software.ligo.org/lscsoft/source/nds2-client-${NDS2_CLIENT_VERSION}.tar.gz"
    - LALSIM="http://software.ligo.org/lscsoft/source/lalsuite/lalsimulation-${LALSIM_VERSION}.tar.gz"


before_install:
  # update pip
  - pip install -q ${PRE} --upgrade pip

  # build and install numpy first
  - pip install -q ${PRE} "numpy>=1.7"

  # build src packages and set 'latest' package versions (if required)
  - source .travis/find-latest-releases.sh
  - source .travis/build-src-dependencies.sh

  # install cython to speed up scipy build
  - travis_retry pip install -q ${PRE} --install-option="--no-cython-compile" Cython

  # install testing dependencies
  - pip install -q ${PRE} coveralls "pytest>=2.8" unittest2

  # need to install astropy 1.1 specifically for py26
  - if [[ ${TRAVIS_PYTHON_VERSION} == '2.6' ]]; then pip install "astropy==1.1"; fi

install:
  # install dependencies (using version-dependent requirements if needed)
  - . .travis/install-requirements.sh
  # add extra dependencies for testing
  # build
  - python setup.py build

script:
  - . .travis/run-tests.sh
  - pip install . -vvv

after_success:
  - coveralls
